'use client'
import {useState} from 'react'; import {faDate,faTime} from '@/lib/format'; import {useRealtime} from '@/hooks/useRealtime'
import {Search as SearchIcon, PackageSearch, RotateCcw, CheckCircle2, Clock3, SlidersHorizontal, X, Download, CheckSquare} from 'lucide-react'
type Status='IN_TRANSIT'|'DELIVERED'|'RETURNED'
const statusLabel=(s:string)=>s==='DELIVERED'?'تحویل':s==='RETURNED'?'برگشتی':'درحال ارسال'
export default function Search(){
 const initial={barcode:'',rider:'',type:'ALL',status:'ALL',from:'',to:''}; const [f,setF]=useState<any>(initial),[rows,setRows]=useState<any[]>([]),[searched,setSearched]=useState(false),[busy,setBusy]=useState(false)
 const [selectedIds,setSelectedIds]=useState<number[]>([]),[bulkStatus,setBulkStatus]=useState<Status>('DELIVERED'),[statusBusy,setStatusBusy]=useState(false)
 async function run(){setBusy(true);try{const data=await (await fetch('/api/search?'+new URLSearchParams(f).toString(),{cache:'no-store'})).json();setRows(data);setSearched(true);setSelectedIds([])}finally{setBusy(false)}}
 useRealtime(()=>{if(searched)run()})
 function toggle(id:number){setSelectedIds(p=>p.includes(id)?p.filter(x=>x!==id):[...p,id])}
 function toggleAll(){setSelectedIds(p=>p.length===rows.length?[]:rows.map(x=>x.id))}
 async function changeStatus(ids:number[],status:Status){if(!ids.length)return;setStatusBusy(true);try{const r=await fetch('/api/scan',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids,status})});const d=await r.json();if(!r.ok){alert(d.error||'خطا در تغییر وضعیت');return}await run()}finally{setStatusBusy(false)}}
 return <><div className="top"><div><div className="eyebrow"><PackageSearch size={13}/> پیدا کردن سریع مرسوله</div><h1>جستجوی پیشرفته</h1><div className="muted">هر چیزی که از مرسوله می‌دانید وارد کنید؛ لازم نیست همه فیلدها پر شوند.</div></div></div>
 <div className="card"><div className="row" style={{justifyContent:'space-between',marginBottom:14}}><div className="row"><SlidersHorizontal size={18}/><b>فیلترها</b></div><button className="btn secondary" onClick={()=>{setF(initial);setRows([]);setSearched(false);setSelectedIds([])}}><X size={14}/> پاک کردن</button></div><div className="form-grid">
 <div><label className="muted">بارکد</label><input className="input" style={{marginTop:6}} placeholder="مثلاً 123456789" value={f.barcode} onChange={e=>setF({...f,barcode:e.target.value})} onKeyDown={e=>e.key==='Enter'&&run()}/></div>
 <div><label className="muted">نام راکب</label><input className="input" style={{marginTop:6}} placeholder="نام کامل یا بخشی از نام" value={f.rider} onChange={e=>setF({...f,rider:e.target.value})} onKeyDown={e=>e.key==='Enter'&&run()}/></div>
 <div><label className="muted">نوع رانشیت</label><select className="select" style={{marginTop:6}} value={f.type} onChange={e=>setF({...f,type:e.target.value})}><option value="ALL">همه نوع‌ها</option><option value="NDX">NDX</option><option value="SAPAPOST">SAPA Post</option></select></div>
 <div><label className="muted">وضعیت</label><select className="select" style={{marginTop:6}} value={f.status} onChange={e=>setF({...f,status:e.target.value})}><option value="ALL">همه وضعیت‌ها</option><option value="IN_TRANSIT">درحال ارسال</option><option value="DELIVERED">تحویل</option><option value="RETURNED">برگشتی</option></select></div>
 <div><label className="muted">از تاریخ</label><input className="input" style={{marginTop:6}} type="date" value={f.from} onChange={e=>setF({...f,from:e.target.value})}/></div>
 <div><label className="muted">تا تاریخ</label><input className="input" style={{marginTop:6}} type="date" value={f.to} onChange={e=>setF({...f,to:e.target.value})}/></div></div>
 <div className="row" style={{marginTop:14,flexWrap:'wrap'}}><button className="btn big" style={{minWidth:160}} onClick={run} disabled={busy}><SearchIcon size={18}/>{busy?'در حال جستجو...':'جستجو'}</button>{searched&&<a className="btn secondary big" href={'/api/export?'+new URLSearchParams(f).toString()}><Download size={17}/> خروجی اکسل همین جستجو</a>}</div></div>
 <div className="card section">{searched&&<div className="search-result-count">{rows.length} نتیجه پیدا شد</div>}
 {searched&&rows.length>0&&<div className="bulk-bar"><label className="select-all"><input type="checkbox" checked={selectedIds.length===rows.length} onChange={toggleAll}/>{selectedIds.length?`${selectedIds.length} مورد انتخاب شده`:'انتخاب همه'}</label><select className="select bulk-select" value={bulkStatus} onChange={e=>setBulkStatus(e.target.value as Status)}><option value="IN_TRANSIT">درحال ارسال</option><option value="DELIVERED">تحویل</option><option value="RETURNED">برگشتی</option></select><button className="btn big" disabled={!selectedIds.length||statusBusy} onClick={()=>changeStatus(selectedIds,bulkStatus)}><CheckSquare size={17}/>{statusBusy?'در حال اعمال...':`تغییر انتخاب‌شده‌ها به ${statusLabel(bulkStatus)}`}</button></div>}
 <div className="table-wrap"><table className="table"><thead><tr><th><input type="checkbox" checked={selectedIds.length===rows.length&&rows.length>0} onChange={toggleAll}/></th><th>بارکد</th><th>راکب</th><th>رانشیت</th><th>تاریخ</th><th>ساعت</th><th>وضعیت</th><th>تغییر وضعیت</th></tr></thead><tbody>{rows.map(i=><tr key={i.id} className={selectedIds.includes(i.id)?'row-selected':''}><td><input type="checkbox" checked={selectedIds.includes(i.id)} onChange={()=>toggle(i.id)}/></td><td dir="ltr" style={{textAlign:'right',fontWeight:800}}>{i.barcode}</td><td>{i.runsheet.rider.name}</td><td>{i.runsheet.type} #{i.runsheet.id}</td><td>{faDate(i.registeredAt)}</td><td>{faTime(i.registeredAt)}</td><td><span className={i.status==='RETURNED'?'badge returned':'badge'}>{i.status==='RETURNED'?<><RotateCcw size={12}/> برگشتی</>:i.status==='DELIVERED'?<><CheckCircle2 size={12}/> تحویل</>:<><Clock3 size={12}/> درحال ارسال</>}</span></td><td><select className="select status-select" value={i.status==='NORMAL'?'IN_TRANSIT':i.status} disabled={statusBusy} onChange={e=>changeStatus([i.id],e.target.value as Status)}><option value="IN_TRANSIT">درحال ارسال</option><option value="DELIVERED">تحویل</option><option value="RETURNED">برگشتی</option></select></td></tr>)}</tbody></table></div>
 {searched&&!rows.length&&<div className="empty"><div className="empty-icon"><PackageSearch size={28}/></div><h3>مرسوله‌ای پیدا نشد</h3><div>فیلترها را کمتر کنید یا بارکد را دوباره بررسی کنید.</div></div>}{!searched&&<div className="empty"><div className="empty-icon"><SearchIcon size={28}/></div><h3>برای شروع جستجو، یکی از فیلترها را وارد کنید</h3><div>جستجو می‌تواند فقط با بارکد، نام راکب یا حتی وضعیت انجام شود.</div></div>}</div></>
}
