'use client'
import {useEffect,useState} from 'react'
import {useRealtime} from '@/hooks/useRealtime'
import {Bike, Plus, Search, Pencil, Power, UserRound, Phone, X} from 'lucide-react'
export default function Riders(){
 const [rows,setRows]=useState<any[]>([]),[q,setQ]=useState(''),[open,setOpen]=useState(false),[form,setForm]=useState<any>({name:'',phone:'',password:''}),[busy,setBusy]=useState(false),[error,setError]=useState('')
 async function load(){setRows(await (await fetch('/api/riders?q='+encodeURIComponent(q),{cache:'no-store'})).json())} useEffect(()=>{load()},[]); useRealtime(load)
 async function save(e:React.FormEvent){e.preventDefault();setError('');setBusy(true);const method=form.id?'PATCH':'POST';const r=await fetch('/api/riders',{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});const d=await r.json();setBusy(false);if(!r.ok){setError(d.error||'خطا در ذخیره اطلاعات');return}setOpen(false);setForm({name:'',phone:''});load()}
 async function toggle(r:any){await fetch('/api/riders',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({...r,active:!r.active})});load()}
 return <><div className="top"><div><div className="eyebrow"><Bike size={13}/> مدیریت افراد</div><h1>راکب‌ها</h1><div className="muted">اضافه‌کردن و مدیریت راکب‌ها با حداقل کلیک.</div></div><button className="btn big" onClick={()=>{setForm({name:'',phone:'',password:''});setError('');setOpen(true)}}><Plus size={18}/> راکب جدید</button></div>
 <div className="card"><div className="row responsive" style={{marginBottom:14}}><div style={{position:'relative',flex:1}}><Search size={17} style={{position:'absolute',right:13,top:13,color:'#94a3b8'}}/><input className="input" style={{paddingRight:40}} value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&load()} placeholder="نام یا شماره موبایل را جستجو کنید..."/></div><button className="btn secondary" onClick={load}>جستجو</button></div><div className="table-wrap"><table className="table"><thead><tr><th>راکب</th><th>موبایل</th><th>وضعیت</th><th>رانشیت‌ها</th><th>عملیات</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td><div className="row"><div className="nav-icon"><UserRound size={18}/></div><b>{r.name}</b></div></td><td dir="ltr" style={{textAlign:'right'}}>{r.phone||'-'}</td><td><span className={r.active?'badge':'badge inactive'}>{r.active?'● فعال':'غیرفعال'}</span></td><td>{r._count.runsheets}</td><td><div className="row"><button className="btn secondary" onClick={()=>{setForm(r);setError('');setOpen(true)}}><Pencil size={14}/> ویرایش</button><button className={r.active?'btn danger':'btn success'} onClick={()=>toggle(r)}><Power size={14}/>{r.active?'غیرفعال':'فعال'}</button></div></td></tr>)}</tbody></table></div>{!rows.length&&<div className="empty"><div className="empty-icon"><Bike size={28}/></div><h3>راکبی پیدا نشد</h3><div>یک راکب جدید اضافه کنید یا عبارت جستجو را تغییر دهید.</div></div>}</div>
 {open&&<div className="modal" onClick={()=>setOpen(false)}><form className="modalbox" onClick={e=>e.stopPropagation()} onSubmit={save}><div className="row" style={{justifyContent:'space-between'}}><div><h3>{form.id?'ویرایش راکب':'افزودن راکب جدید'}</h3><p className="muted">نام، شماره موبایل و رمز عبور برای ورود راکب ثبت می‌شود. در ویرایش، رمز عبور اختیاری است.</p></div><button type="button" className="btn secondary" style={{padding:9}} onClick={()=>setOpen(false)}><X size={16}/></button></div>{error&&<div className="error" style={{marginBottom:12}}>{error}</div>}<label className="muted">نام و نام خانوادگی</label><div style={{position:'relative',margin:'7px 0 13px'}}><UserRound size={17} style={{position:'absolute',right:13,top:13,color:'#94a3b8'}}/><input autoFocus className="input" style={{paddingRight:40}} placeholder="مثلاً علی رضایی" value={form.name} onChange={e=>setForm({...form,name:e.target.value})}/></div><label className="muted">شماره موبایل</label><div style={{position:'relative',margin:'7px 0 18px'}}><Phone size={17} style={{position:'absolute',right:13,top:13,color:'#94a3b8'}}/><input className="input" style={{paddingRight:40}} placeholder="09xxxxxxxxx" value={form.phone||''} onChange={e=>setForm({...form,phone:e.target.value})}/></div><label className="muted">رمز عبور ورود</label><input className="input" style={{margin:'7px 0 18px'}} type="password" placeholder={form.id?'برای تغییر رمز وارد کنید':'حداقل 6 کاراکتر'} value={form.password||''} onChange={e=>setForm({...form,password:e.target.value})}/><div className="row"><button className="btn big" disabled={busy}>{busy?'در حال ذخیره...':'ذخیره راکب'}</button><button type="button" className="btn secondary big" onClick={()=>setOpen(false)}>انصراف</button></div></form></div>}</>
}
