'use client'
import {useEffect,useState} from 'react'
import {DatabaseBackup, ShieldCheck, RotateCcw, HardDrive, CheckCircle2, AlertTriangle} from 'lucide-react'
export default function Backup(){
 const [files,setFiles]=useState<string[]>([]),[msg,setMsg]=useState<any>(null),[busy,setBusy]=useState(false); async function load(){setFiles(await (await fetch('/api/backup',{cache:'no-store'})).json())} useEffect(()=>{load()},[])
 async function backup(){setBusy(true);const d=await (await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'})).json();setMsg({ok:true,text:'نسخه پشتیبان ساخته شد: '+d.file});setBusy(false);load()}
 async function restore(file:string){if(!confirm('اطلاعات فعلی با این نسخه پشتیبان جایگزین شود؟'))return;setBusy(true);const r=await fetch('/api/backup',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'restore',file})});setBusy(false);setMsg(r.ok?{ok:true,text:'بازیابی انجام شد. اطلاعات تمام دستگاه‌ها از این نسخه خوانده می‌شود.'}:{ok:false,text:'بازیابی انجام نشد.'})}
 return <><div className="top"><div><div className="eyebrow"><ShieldCheck size={13}/> امنیت داده‌ها</div><h1>پشتیبان‌گیری</h1><div className="muted">همه اطلاعات روی کامپیوتر اصلی است؛ از اینجا یک نسخه امن بسازید.</div></div><button className="btn big" disabled={busy} onClick={backup}><DatabaseBackup size={18}/>{busy?'لطفاً صبر کنید...':'ایجاد Backup جدید'}</button></div>
 <div className="grid" style={{gridTemplateColumns:'repeat(2,minmax(0,1fr))'}}><div className="card hero-card"><div className="stat-icon"><HardDrive size={22}/></div><h3>دیتابیس مرکزی</h3><div className="muted" style={{lineHeight:1.9}}>کامپیوتر اصلی تنها محل نگهداری دیتابیس است. سیستم‌های دیگر شبکه مستقیماً به همین اطلاعات دسترسی دارند.</div></div><div className="card hero-card"><div className="stat-icon" style={{background:'#ecfdf5',color:'#059669'}}><ShieldCheck size={22}/></div><h3>پیشنهاد عملی</h3><div className="muted" style={{lineHeight:1.9}}>در پایان هر روز کاری یک Backup بسازید و فایل‌های مهم را روی یک حافظه جدا نیز نگهداری کنید.</div></div></div>
 {msg&&<div className={`section ${msg.ok?'success':'error'}`}>{msg.ok?<CheckCircle2 size={16} style={{verticalAlign:'middle',marginLeft:6}}/>:<AlertTriangle size={16} style={{verticalAlign:'middle',marginLeft:6}}/>}{msg.text}</div>}
 <div className="card section"><div className="row" style={{justifyContent:'space-between',marginBottom:12}}><h3 style={{margin:0}}>نسخه‌های موجود</h3><span className="chip">{files.length} نسخه</span></div>{files.length?<div className="runs-list">{files.map(f=><div className="runs-item" key={f}><div className="row" style={{justifyContent:'space-between'}}><div className="row"><div className="nav-icon"><DatabaseBackup size={17}/></div><span dir="ltr">{f}</span></div><button className="btn secondary" onClick={()=>restore(f)}><RotateCcw size={14}/> بازیابی</button></div></div>)}</div>:<div className="empty"><div className="empty-icon"><DatabaseBackup size={28}/></div><h3>هنوز Backup ندارید</h3><div>برای ساخت اولین نسخه، دکمه بالای صفحه را بزنید.</div></div>}</div></>
}
